In [37]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, r2_score, recall_score, confusion_matrix, classification_report

In [20]:
df = pd.read_csv("Iris.csv")

In [21]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [23]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [24]:
le = LabelEncoder()
X = df.drop("Species", axis=1)
Y = le.fit_transform(df["Species"])

In [26]:
nv = GaussianNB()

In [27]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [28]:
nv.fit(X_train, Y_train)

GaussianNB()

In [30]:
y_pred = nv.predict(X_test)

In [ ]:
acc = accuracy_score(Y_test, y_pred)
recall = recall_score(Y_test, y_pred, average="macro")
from sklearn.metrics import average_precision_score
cm = confusion_matrix(Y_test, y_pred)
report = classification_report(Y_test, y_pred)

print("Accuracy:", acc)
print("Recall:", recall)
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

Accuracy: 1.0
Recall: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [38]:
scores = cross_val_score(nv, X, Y, cv=5)

print("CV Accuracy:", scores)
print("Mean:", scores.mean())

CV Accuracy: [0.96666667 1.         1.         1.         1.        ]
Mean: 0.9933333333333334

Logistic Regression

In [42]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [45]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [46]:
lr_y_pred = model.predict(X_test)

In [47]:
acc = accuracy_score(Y_test, lr_y_pred)
recall = recall_score(Y_test, lr_y_pred, average="macro")
cm = confusion_matrix(Y_test, lr_y_pred)
report = classification_report(Y_test, lr_y_pred)

print("Accuracy:", acc)
print("Recall:", recall)
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

Accuracy: 1.0
Recall: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

KNN

In [49]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [50]:
scaler = StandardScaler()

In [51]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [52]:
for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, Y_train)
    print("neighbours ", k, " score ", knn.score(X_test, Y_test))

neighbours  1  score  1.0
neighbours  2  score  1.0
neighbours  3  score  1.0
neighbours  4  score  1.0
neighbours  5  score  1.0
neighbours  6  score  1.0
neighbours  7  score  1.0
neighbours  8  score  1.0
neighbours  9  score  1.0
neighbours  10  score  1.0